export const quotes = [
  "Trade. Play. Win.",
  "Risk. Strategy. Reward.",
  "Bet. Compete. Conquer.",
  "Analyze. Execute. Dominate.",
  "Focus. Predict. Triumph.",
  "Trade with logic, not emotion",
  "Games test skill, not luck",
  "Patience wins the trading game",
  "Every move counts in trading",
  "Win or learn, never lose",
  "Market rewards discipline daily",
  "Games sharpen the mind",
  "Risk smart, trade smarter",
  "Strategy beats speed every time",
  "Play the long game in markets",
  "Read charts like a game board",
  "Trade only when ready",
  "Skill grows with each trade",
  "Luck fades, skill stays",
  "Games teach winning mindset",
  "Profit loves patience",
  "Trade less, gain more",
  "Every trade is a lesson",
  "Games mirror real life",
  "Confidence grows with wins",
  "Plan the trade, play the plan",
  "Games reward persistence",
  "Markets punish the careless",
  "Focus is the ultimate weapon",
  "Every trade is a game move",
  "Learn rules, then break wisely",
  "Discipline turns losses to wins",
  "Games reward creative thinking",
  "Adapt fast, survive longer",
  "Trade without fear or greed",
  "Risk is the price of profit",
  "Markets reward the prepared",
  "Think like a player, act like a trader",
  "Games keep the mind sharp",
  "Trade with a clear plan",
  "Skill beats luck every round",
  "Patience is a trading superpower",
  "Games teach resource management",
  "Every chart tells a story",
  "Losses are part of the game",
  "Markets reward the consistent",
  "Play the probabilities",
  "Games test your limits",
  "Trade for growth, not thrill",
  "Strategy wins in long run",
  "Focus turns players into champions",
  "Plan ahead, react fast",
  "Markets love disciplined players",
  "Games demand practice daily",
  "Winning comes from preparation",
  "Trade like a grandmaster",
  "Analyze before you act",
  "Games sharpen decision skills",
  "Patience builds trading fortunes",
  "Every move should have purpose",
  "Markets punish impatience",
  "Games reward those who adapt",
  "Control the game, control yourself",
  "Risk less, gain more",
  "Plan every trading move",
  "Games teach calculated risk",
  "Focus on the end goal",
  "Markets move in patterns",
  "Observe, learn, then act",
  "Games reward quick thinking",
  "Trading is the ultimate game",
  "Patience wins championships",
  "Keep score, track progress",
  "Markets reward the informed",
  "Stay calm under pressure",
  "Games reveal hidden skills",
  "Trade with eyes wide open",
  "Every play teaches something new",
  "Discipline drives trading success",
  "Adapt or lose the game",
  "Markets reward the sharp-minded",
  "Think ahead like a chess player",
  "Games make the mind agile",
  "Profit follows smart moves",
  "Stay in the game longer",
  "Markets demand mental strength",
  "Games mirror market psychology",
  "Plan two steps ahead",
  "Trade like a strategist",
  "Luck helps, skill rules",
  "Games build competitive spirit",
  "Win small, win often",
  "Markets reward patience",
  "Stay disciplined to stay profitable",
  "Games sharpen the competitive edge",
  "Master the rules to win",
  "Every loss is tuition",
  "Markets teach humility",
  "Practice until trading feels natural",
  "Games demand your best",
  "Cut losses fast, let profits run",
  "Markets reward smart exits",
  "Play to your strengths",
  "Games keep strategy alive",
  "Risk wisely, not wildly",
  "Markets move on emotion",
  "Learn the game's flow",
  "Patience makes better traders",
  "Games reward risk-takers",
  "Trade with purpose",
  "Stay consistent to win",
  "Games develop quick reflexes",
  "Profit is a side effect of discipline",
  "Markets reward cool heads",
  "Think like a gamer, act like a trader",
  "Games build resilience",
  "Protect your capital first",
  "Stay focused through the noise",
  "Games keep you sharp",
  "Every trade is a move",
  "Markets reward those who wait",
  "Game on, trade on",
  "Plan your exit before entry",
  "Stay adaptable to win",
  "Games reward persistence",
  "Win slow, win steady",
  "Markets favor the observant",
  "Be a player, not a gambler",
  "Games teach decision making",
  "Trade smart, play smart",
  "Every win starts with a plan",
  "Markets punish overconfidence",
  "Games train strategic thinking",
  "Cut bad trades fast",
  "Stay humble in wins",
  "Games make you think ahead",
  "Trade in your comfort zone",
  "Plan, execute, review",
  "Markets favor the disciplined",
  "Adapt strategies as needed",
  "Games reveal your mindset",
  "Keep trading simple",
  "Stay sharp, stay profitable",
  "Games reward mental agility",
  "Follow the trading plan",
  "Risk less when unsure",
  "Markets punish laziness",
  "Train daily like an athlete",
  "Games reward preparation",
  "Trade only when ready",
  "Stay patient in the game",
  "Markets reward learning",
  "Games test endurance",
  "Play the long-term game",
  "Never stop improving",
  "Games keep you learning",
  "Focus on consistent results",
  "Trade when odds are high",
  "Markets punish recklessness",
  "Games reveal true skill",
  "Track every trade",
  "Practice with purpose",
  "Games reward strategic patience",
  "Trade small, think big",
  "Learn from every outcome",
  "Markets reward self-control",
  "Games test adaptability",
  "Avoid emotional decisions",
  "Play to improve, not just win",
  "Stay flexible under pressure",
  "Games reward creative play",
  "Trade with intention",
  "Keep losses small",
  "Markets reward analysis",
  "Games make you think differently",
  "Stay ready for the next move",
  "Plan before you play",
  "Trade when the setup is right",
  "Games test patience and skill",
  "Focus on quality trades",
  "Markets reward knowledge",
  "Adapt to the market game",
  "Games build mental toughness",
  "Always review your game",
  "Cut losses, keep winners",
  "Stay objective while trading",
  "Games reward consistency",
  "Think long term, act now",
  "Plan every trading session",
  "Markets punish hesitation",
  "Games teach situational awareness",
  "Trade without chasing",
  "Keep your head in the game",
  "Markets reward sharp focus",
  "Games build confidence",
  "Never overtrade",
  "Stay disciplined under pressure",
  "Games demand full attention",
  "Trade with clarity",
  "Protect your wins",
  "Markets reward patience and skill",
  "Games test timing",
  "Plan to win, prepare to lose",
  "Trade with balance",
  "Keep practicing daily",
  "Games build foresight",
  "Stay calm when losing",
  "Markets punish panic",
  "Games reward strategic depth",
  "Win more by risking less",
  "Trade only high-quality setups",
  "Stay focused on your edge",
  "Markets favor the smart player",
  "Games reveal competitive drive",
  "Plan for both up and down",
  "Trade to survive first",
  "Games reward observation",
  "Stay grounded in the game",
  "Markets demand consistency",
  "Play every move with purpose",
  "Trade at your own pace",
  "Games reward long-term focus",
  "Review your mistakes",
  "Markets punish poor planning",
  "Games test your patience",
  "Stay in control of risk",
  "Trade with conviction",
  "Keep improving daily",
  "Games build problem-solving skills",
  "Profit comes from patience",
  "Markets reward discipline over speed",
  "Games make patience fun",
  "Every trade tells a story",
  "Stay mindful in the game",
  "Markets reward those who prepare",
  "Games sharpen strategy skills",
  "Trade without overthinking",
  "Stay consistent in wins",
  "Markets punish greed",
  "Games reward skillful play",
  "Risk small to learn big",
  "Trade with an edge",
  "Stay engaged in the market",
  "Games demand critical thinking",
  "Markets reward adaptability",
  "Games keep you strategic",
  "Think like a champion",
  "Stay committed to improvement",
  "Markets reward preparation",
  "Games demand focus",
  "Trade with a purpose",
  "Stay ahead by staying ready",
  "Games reward mental clarity",
  "Markets favor disciplined patience",
  "Games make learning fun",
  "Trade to win the war",
  "Stay calm during storms",
  "Markets punish impatience and fear",
  "Games reward precision",
  "Trade slow to win fast",
  "Stay strong under pressure",
  "Games build analytical thinking",
  "Markets reward consistent habits",
  "Games test quick decision-making",
  "Trade when opportunity knocks",
  "Stay disciplined in strategy",
  "Games reward calculated moves",
  "Markets favor the resilient",
  "Games sharpen mental focus",
  "Trade without chasing losses",
  "Stay objective at all times",
  "Games reward adaptability and skill",
  "Markets favor the patient",
  "Games teach critical evaluation",
  "Trade for the right reasons",
  "Stay ready to pivot",
  "Games reward timing",
  "Markets favor observation",
  "Games teach focus under stress",
  "Trade smart, live better",
  "Stay ahead of the crowd",
  "Games reward resourcefulness",
  "Markets reward long-term focus",
  "Games test resilience",
  "Trade when the setup is clear",
  "Stay sharp in the game",
  "Games reward strategic patience",
  "Markets reward humble winners",
  "Games build decision-making power",
  "Trade your edge relentlessly",
  "Stay prepared every session",
  "Games demand mental resilience",
  "Markets reward the disciplined few",
  "Games keep the mind in motion",
  "Trade as if every move matters",
  "Stay calm when profits swing",
  "Games reward the prepared mind",
  "Markets punish the unprepared",
  "Games make winning possible daily",
  "Trade with logic every time",
  "Stay in learning mode",
  "Games reward tactical awareness",
  "Markets reward careful planning",
  "Games demand consistent practice",
  "Trade without fear of loss",
  "Stay in the winner's mindset",
  "Games reward steady growth",
  "Markets reward knowledge seekers",
  "Games teach competitive patience",
  "Trade like a champion player",
  "Stay calm when stakes are high",
  "Games reward commitment",
  "Markets reward unwavering focus",
  "Games build market-like thinking",
  "Trade knowing the rules",
  "Stay confident in your plan",
  "Games reward the relentless",
  "Markets reward sharp execution",
  "Games demand thoughtful play",
  "Trade to improve your craft",
  "Stay resilient through losses",
  "Games reward persistent learners",
  "Markets reward calculated patience",
  "Games teach victory and defeat",
  "Trade smart, win big",
  "Stay adaptable to survive",
  "Games reward those who persist",
  "Markets reward cool decision-making",
  "Games keep your edge alive",
  "Trade every day like a final",
  "Stay humble, stay hungry",
  "Games reward skill over luck",
  "Markets reward constant learning",
  "Games demand your best self",
  "Trade to protect your capital",
  "Stay mindful of every risk",
  "Games reward the observant mind",
  "Markets reward the strategic",
  "Games mirror life’s challenges",
  "Trade when ready, not before",
  "Stay sharp, stay alive",
  "Games reward precision timing",
  "Markets favor prepared players",
  "Games teach smart risks",
  "Trade the plan, not the noise",
  "Stay disciplined for long-term success",
  "Games reward tactical thinking",
  "Markets reward clarity and calm",
  "Games keep ambition alive",
  "Trade for growth over glory",
  "Stay wise in tough markets",
  "Games reward long-term strategies",
  "Markets punish careless risk",
  "Games test courage",
  "Trade the trend smartly",
  "Stay in tune with the market",
  "Games reward adaptability over speed",
  "Markets favor the thoughtful",
  "Games reward consistent skill",
  "Trade steady, win steady",
  "Stay alert to market moves",
  "Games teach patience through play",
  "Markets reward consistency in effort",
  "Games keep you sharp-minded",
  "Trade to master, not gamble",
  "Stay strong when odds are low",
  "Games reward mastery over luck",
  "Markets reward the careful planner",
  "Games build the winner's mindset",
  "Markets reward the long-term thinker",
  "Games reward flawless execution",
  "Trade with confidence and clarity",
  "Stay disciplined in every round",
  "Games teach the value of timing",
  "Markets reward the patient planner",
  "Games keep strategy alive and sharp",
  "Trade to strengthen your skills",
  "Stay calm when markets move fast",
  "Games reward practice over luck",
  "Markets punish emotional reactions",
  "Games test your ability to adapt",
  "Trade the facts, not opinions",
  "Stay humble after every win",
  "Games reward creative problem-solving",
  "Markets reward steady discipline",
  "Games demand constant improvement",
  "Trade without fear or greed",
  "Stay ahead with preparation",
  "Games reward focus under fire",
  "Markets favor the calculated risk-taker",
  "Games build situational awareness",
  "Trade with patience as armor",
  "Stay committed to the process",
  "Games reward those who think ahead",
  "Markets reward those who plan early",
  "Games keep the mind competitive",
  "Trade to survive before thriving",
  "Stay ready for every opportunity",
  "Games reward sharp observation",
  "Markets reward strategic restraint",
  "Games teach calculated decision-making",
  "Trade slow when uncertain",
  "Stay disciplined through volatility",
  "Games reward smart adaptation",
  "Markets punish careless trades",
  "Games keep you sharp and ready",
  "Trade like every point matters",
  "Stay aware of risk at all times",
  "Games reward the well-prepared",
  "Markets reward the humble learner",
  "Games demand total attention",
  "Trade when the odds align",
  "Stay alert to changing trends",
  "Games reward timing over speed",
  "Markets favor those who prepare",
  "Games sharpen decision-making power",
  "Trade to protect before profit",
  "Stay consistent with your methods",
  "Games reward precision under pressure",
  "Markets reward sharp timing",
  "Games teach patience in competition",
  "Trade without chasing the market",
  "Stay strong during losing streaks",
  "Games reward planning ahead",
  "Markets favor those with foresight",
  "Games reward strategic risk",
  "Trade your strengths, not your fears",
  "Stay in control of your moves",
  "Games build confidence through play",
  "Markets reward those who adapt fast",
  "Games reward calm thinking",
  "Trade with a purpose every time",
  "Stay on plan even when tempted",
  "Games reward consistent practice",
  "Markets reward sharp adaptability",
  "Games test your mental resilience",
  "Trade knowing when not to trade",
  "Stay patient for the right moment",
  "Games reward sharp tactical plays",
  "Markets reward the prepared trader",
  "Games reward planning and patience",
  "Trade smart to last long",
  "Stay cool when markets heat up",
  "Games reward mastery over time",
  "Markets favor those who stay calm",
  "Games test strategic depth",
  "Trade with long-term vision",
  "Stay humble when the market is kind",
  "Games reward quick adjustments",
  "Markets punish careless confidence",
  "Games build adaptability skills",
  "Trade with steady focus",
  "Stay engaged with the learning process",
  "Games reward skillful patience",
  "Markets reward sharp awareness",
  "Games keep your competitive edge",
  "Trade like a tournament player",
  "Stay consistent under market pressure",
  "Games reward those who analyze well",
  "Markets reward the cautious optimist",
  "Games teach tactical awareness",
  "Trade as if each move is final",
  "Stay grounded during big wins",
  "Games reward preparation and skill",
  "Markets favor careful observation",
  "Games keep the mind alert",
  "Trade without ego",
  "Stay prepared for sudden changes",
  "Games reward the adaptable mind",
  "Markets reward calm execution",
  "Games test patience under pressure",
  "Trade to control, not chase",
  "Stay focused on risk management",
  "Games reward long-term dedication",
  "Markets favor those who plan well",
  "Games reward calculated plays",
  "Trade with skill, not luck",
  "Stay clear-headed during setbacks",
  "Games reward learning from mistakes",
  "Markets punish overconfidence quickly",
  "Games demand your best strategy",
  "Trade as part of a bigger plan",
  "Stay patient to maximize gains",
  "Games reward quiet consistency",
  "Markets favor the level-headed",
  "Games sharpen strategic discipline",
  "Trade with your head, not heart",
  "Stay in control during chaos",
  "Games reward those who think fast",
  "Markets reward adaptable thinkers",
  "Games reward resilience and patience",
  "Trade to improve every session",
  "Stay vigilant in all conditions",
  "Games reward strategic timing",
  "Markets reward data-driven moves",
  "Games keep your brain competitive",
  "Trade to protect capital first",
  "Stay adaptable to win consistently",
  "Games reward creative execution",
  "Markets favor disciplined traders",
  "Games teach winning through patience",
  "Trade with the big picture in mind",
  "Stay committed to your edge",
  "Games reward mastery through repetition",
  "Markets reward smart exits",
  "Games reward flexible strategies",
  "Trade only the best opportunities",
  "Stay sharp during quiet markets",
  "Games build calculated courage",
  "Markets reward consistent habits",
  "Games keep you in mental shape",
  "Trade with confidence in your plan",
  "Stay disciplined to reduce risk",
  "Games reward controlled aggression",
  "Markets favor those who learn fast",
  "Games test endurance under pressure",
  "Trade like each move matters",
  "Stay alert for false signals",
  "Games reward deep preparation",
  "Markets reward timing and patience",
  "Games teach tactical patience",
  "Trade knowing your limits",
  "Stay humble to keep learning",
  "Games reward those who think twice",
  "Markets punish the careless trader",
  "Games sharpen quick judgment",
  "Trade for quality, not quantity",
  "Stay clear of unnecessary risks",
  "Games reward high-percentage moves",
  "Markets reward accurate analysis",
  "Games test your adaptability daily",
  "Trade with a purpose in mind",
  "Stay prepared for any outcome",
  "Games reward strategic vision",
  "Markets favor the observant trader",
  "Games reward patience under fire",
  "Trade smart when stakes are high",
  "Stay in control of your capital",
  "Games build confidence in decisions",
  "Markets reward those who plan ahead",
  "Games reward consistent improvement",
  "Trade without emotional baggage",
  "Stay focused when momentum shifts",
  "Games reward adaptive strategies",
  "Markets reward measured decisions",
  "Games sharpen long-term thinking",
  "Trade knowing your goals",
  "Stay committed to discipline",
  "Games reward precise execution",
  "Markets favor steady players",
  "Games reward mental alertness",
  "Trade to protect your future",
  "Stay sharp against market noise",
  "Games reward calm under pressure",
  "Markets punish impulsive moves",
  "Games reward a patient mind",
  "Trade with calculated intent",
  "Stay strong in volatile markets",
  "Games reward preparation over speed",
  "Markets reward the thoughtful trader",
  "Games demand constant focus",
  "Trade with knowledge and patience",
  "Stay cool under trading stress",
  "Games reward risk management",
  "Markets favor consistent winners",
  "Games reward strategy over chance",
  "Trade slow in a fast market",
  "Stay consistent with your approach",
  "Games reward well-timed moves",
  "Markets reward humble execution",
  "Games test your adaptability skills",
  "Trade to learn before earning",
  "Stay calm when pressure builds",
  "Games reward patience in adversity",
  "Markets punish rushing in",
  "Games sharpen foresight",
  "Trade for steady progress",
  "Stay watchful for better setups",
  "Games reward methodical play",
  "Markets favor careful study",
  "Games keep your strategy sharp",
  "Trade with market respect",
  "Stay disciplined through success",
  "Games reward those who improve",
  "Markets reward risk-aware players",
  "Games demand calculated courage",
  "Trade within your limits",
  "Stay grounded in your analysis",
  "Games reward patience and planning",
  "Markets favor those who prepare daily",
  "Games reward high-level focus",
  "Trade with confidence after analysis",
  "Stay composed during losses",
  "Games reward consistent thinking",
  "Markets reward deliberate action",
  "Games keep your mind battle-ready",
  "Trade when market conditions align",
  "Stay aware of your emotions",
  "Games reward tactical thinking",
  "Markets punish careless optimism",
  "Games reward discipline above all",
  "Trade to master the process",
  "Stay patient for the right trade",
  "Games reward smart preparation",
  "Markets reward the steady hand",
  "Games build mental strength",
  "Trade with a purpose every day",
  "Stay strategic, not impulsive",
  "Games reward thoughtful execution",
  "Markets reward those who adapt fast",
  "Games reward consistent habits",
  "Trade slow, trade smart",
  "Stay disciplined in analysis",
  "Games reward clarity of thought",
  "Markets favor the prepared few",
  "Games reward sharp reflexes",
  "Trade to preserve your capital",
  "Stay calm when trends reverse",
  "Games reward strategic control",
  "Markets punish the overconfident",
  "Games test your ability to wait",
  "Trade like a calculated risk-taker",
  "Stay vigilant for new patterns",
  "Games reward the consistent planner",
  "Markets favor careful decision-making",
  "Games reward deep focus",
  "Trade without distractions",
  "Stay humble when markets are kind",
  "Games reward the patient strategist",
  "Markets reward long-term commitment",
  "Games build a winning mindset",
  "Trade only with clear signals",
  "Stay observant in the game",
  "Games reward strategic flexibility",
  "Markets punish chasing trades",
  "Games sharpen your competitive spirit",
  "Trade with patience and skill",
  "Stay committed to the learning path",
  "Games reward preparation above speed",
  "Markets reward calm precision",
  "Games test your adaptability often",
  "Trade when you have the edge",
  "Stay consistent to grow results",
  "Games reward thinking ahead",
  "Markets reward those who never rush",
  "Games reward consistent effort",
  "Trade for long-term gains",
  "Stay calm when opportunities fade",
  "Games sharpen your instincts",
  "Markets punish the distracted player",
  "Games reward patience under pressure",
  "Trade with strategic patience",
  "Stay alert for sudden shifts",
  "Games reward focus and foresight",
  "Markets reward consistent study",
  "Games reward learning from setbacks",
  "Trade smart in all conditions",
  "Stay clear-headed in chaos",
  "Games reward the resilient player",
  "Markets favor those with patience",
  "Games sharpen market instincts",
  "Trade to win over time",
  "Stay disciplined in every session",
  "Games reward tactical adjustments",
  "Markets punish poor preparation",
  "Games build disciplined habits",
  "Trade to master your emotions",
  "Stay aware of every trade",
  "Games reward the mindful player",
  "Markets reward strategic calmness",
  "Games demand critical awareness",
  "Trade without fear of missing out",
  "Stay focused on process over results",
  "Games reward strategy refinement",
  "Markets favor the calm planner",
  "Games reward steady progression",
  "Trade smart and steady",
  "Stay sharp under market stress",
  "Games reward planning ahead",
  "Markets punish the impatient",
  "Games reward patience in pursuit",
  "Trade with clarity in mind",
  "Stay disciplined in execution",
  "Games build the power of foresight",
  "Markets reward well-timed patience",
  "Games reward consistent mastery",
  "Trade slow to grow",
  "Stay humble in success",
  "Games reward calculated persistence",
  "Markets favor the thoughtful learner",
];